export default [
    [
        { glyph: '`', color: 'finger-5', size: 'small', code: 192 },
        { glyph: '1', color: 'finger-5', size: 'key', code: 49 },
        { glyph: '2', color: 'finger-4', size: 'key', code: 50 },
        { glyph: '3', color: 'finger-3', size: 'key', code: 51 },
        { glyph: '4', color: 'finger-2-left', size: 'key', code: 52 },
        { glyph: '5', color: 'finger-2-left', size: 'key', code: 53 },
        { glyph: '6', color: 'finger-2-left', size: 'key', code: 54 },
        { glyph: '7', color: 'finger-2-right', size: 'key', code: 55 },
        { glyph: '8', color: 'finger-3', size: 'key', code: 56 },
        { glyph: '9', color: 'finger-4', size: 'key', code: 57 },
        { glyph: '0', color: 'finger-5', size: 'key', code: 48 },
        { glyph: '-', color: 'finger-5', size: 'key', code: 189 },
        { glyph: '=', color: 'finger-5', size: 'key', code: 187 },
        { glyph: 'Backspace', color: 'grey', size: 'command', code: 8 }
    ],
    [
        { glyph: 'Tab', color: 'grey', size: 'command', code: 9 },
        { glyph: 'Q', color: 'finger-5', size: 'key', code: 81 },
        { glyph: 'W', color: 'finger-4', size: 'key', code: 87 },
        { glyph: 'E', color: 'finger-3', size: 'key', code: 69 },
        { glyph: 'R', color: 'finger-2-left', size: 'key', code: 82 },
        { glyph: 'T', color: 'finger-2-left', size: 'key', code: 84 },
        { glyph: 'Y', color: 'finger-2-right', size: 'key', code: 89 },
        { glyph: 'U', color: 'finger-2-right', size: 'key', code: 85 },
        { glyph: 'I', color: 'finger-3', size: 'key', code: 73 },
        { glyph: 'O', color: 'finger-4', size: 'key', code: 79 },
        { glyph: 'P', color: 'finger-5', size: 'key', code: 80 },
        { glyph: '[', color: 'finger-5', size: 'key', code: 219 },
        { glyph: ']', color: 'finger-5', size: 'key', code: 221 },
        { glyph: '\\', color: 'grey', size: 'command', code: 220 },
    ],
    [
        { glyph: 'Caps Lock', color: 'grey', size: 'command', code: 20 },
        { glyph: 'A', color: 'finger-5', size: 'key', code: 65 },
        { glyph: 'S', color: 'finger-4', size: 'key', code: 83 },
        { glyph: 'D', color: 'finger-3', size: 'key', code: 68 },
        { glyph: 'F', color: 'finger-2-left', size: 'key', code: 70 },
        { glyph: 'G', color: 'finger-2-left', size: 'key', code: 71 },
        { glyph: 'H', color: 'finger-2-right', size: 'key', code: 72 },
        { glyph: 'J', color: 'finger-2-right', size: 'key', code: 74 },
        { glyph: 'K', color: 'finger-3', size: 'key', code: 75 },
        { glyph: 'L', color: 'finger-4', size: 'key', code: 76 },
        { glyph: ';', color: 'finger-5', size: 'key', code: 186 },
        { glyph: '\'', color: 'finger-5', size: 'key', code: 222 },
        { glyph: 'Enter', color: 'grey', size: 'command', code: 13 },
    ],
    [
        { glyph: 'Shift', color: 'grey', size: 'command', code: 16 },
        { glyph: 'Z', color: 'finger-5', size: 'key', code: 90 },
        { glyph: 'X', color: 'finger-4', size: 'key', code: 88 },
        { glyph: 'C', color: 'finger-3', size: 'key', code: 67 },
        { glyph: 'V', color: 'finger-2-left', size: 'key', code: 86 },
        { glyph: 'B', color: 'finger-2-left', size: 'key', code: 66 },
        { glyph: 'N', color: 'finger-2-right', size: 'key', code: 78 },
        { glyph: 'M', color: 'finger-2-right', size: 'key', code: 77 },
        { glyph: ',', color: 'finger-3', size: 'key', code: 188 },
        { glyph: '.', color: 'finger-4', size: 'key', code: 190 },
        { glyph: '/', color: 'finger-5', size: 'key', code: 191 },
        { glyph: 'Shift', color: 'grey', size: 'command', code: 16 },
    ], [
        { glyph: 'Ctrl', color: 'grey', size: 'key', code: 17 },
        { glyph: '', color: 'grey', size: 'key' },
        { glyph: 'Alt', color: 'grey', size: 'key', code: 18 },
        { glyph: ' ', color: 'grey', size: 'space', code: 32 },
        { glyph: 'Alt', color: 'grey', size: 'key', code: 18 },
        { glyph: '', color: 'grey', size: 'key' },
        { glyph: 'Ctrl', color: 'grey', size: 'key', code: 17 }
    ]
];
